# Generated by Django 6.0.6 on 2026-06-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionjob',
            name='input_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='outputs/'),
        ),
    ]
