# Generated by Django 6.0.6 on 2026-07-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converters', '0002_alter_conversionjob_input_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='output_format',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
