# Generated by Django 6.0.6 on 2026-07-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converters', '0003_conversionjob_output_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
