# Generated by Django 5.2.16 on 2026-07-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converters', '0004_conversionjob_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
